version: '3.4'

services:
  web:
    build: ./
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
    - db
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: contact
      POSTGRES_PASSWORD: contact
      POSTGRES_DB: contact
