version: '3.4'

services:
  web:
    build: ./
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
    - db
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: contact
      POSTGRES_PASSWORD: contact
      POSTGRES_DB: contact
  livereload:
    build:
      context: ./
      target: build
    command: npm run-script watch
    volumes:
      - /code/assets/output:/code/assets/output:rw
    ports:
      - "8081:8081"
