# Generated by Django 2.1.1 on 2018-09-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180903_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='added_by',
        ),
    ]
